id: P008122
initial_creation_type: ocr
source_metadata:
  id: bdr:W19895
  title: དམར་མཆོད་ཀྱི་ཉེས་དམིགས
  author: ''
  volumes:
    3ebbfb7cb6a04be8b415d94596929ad2:
      image_group_id: I1CZ2005
      title: ''
      volume_number: 1
      total_pages: 34
ebook_metadata:
  title: དམར་མཆོད་ཀྱི་ཉེས་དམིགས
  author: ''
  sku: P008122
  cover: cover.jpg
  layers:
  - pagination
