id: P008122
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:03:10.264184
source_metadata:
  id: bdr:W19895
  title: དམར་མཆོད་ཀྱི་ཉེས་དམིགས
  author: ''
  volumes:
    96f55c4d2455475d8bc5b7bab20d34ff:
      image_group_id: I1CZ2005
      title: Volume 1 of dmar mchod kyi nyes dmigs
      volume_number: 1
      total_pages: 34
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
